var searchData=
[
  ['capture_20it_20on_20video_20similarly_20returning_20to_20start_20was_20not_20achieved_20consistently_20either_20although_20attempts_20to_20do_20so_20were_20made_0',['Video showing Romi traveling from the start block to the far side of the obstacle. Romi navigates along the path using its reflectance sensor until it hits the obstacle. Then, Romi uses an IMU to navigate around the wall according to its heading. Unfortunately, we were unable to get Romi to consistently begin following the line again after navigating the obstacle, and were unable to capture it on video. Similarly, returning to start was not achieved consistently either, although attempts to do so were made.',['../index.html#autotoc_md12',1,'']]],
  ['chassis_1',['Pololu Romi Chassis',['../index.html#autotoc_md6',1,'']]],
  ['clear_2',['clear',['../classtask__share_1_1_queue.html#a0d4b70d239eb7244ff3b7e54d4a4981e',1,'task_share::Queue']]],
  ['components_3a_3',['Wiring diagram for the ROMI and required electronic components:',['../index.html#autotoc_md11',1,'']]],
  ['consistently_20begin_20following_20the_20line_20again_20after_20navigating_20the_20obstacle_20and_20were_20unable_20to_20capture_20it_20on_20video_20similarly_20returning_20to_20start_20was_20not_20achieved_20consistently_20either_20although_20attempts_20to_20do_20so_20were_20made_4',['Video showing Romi traveling from the start block to the far side of the obstacle. Romi navigates along the path using its reflectance sensor until it hits the obstacle. Then, Romi uses an IMU to navigate around the wall according to its heading. Unfortunately, we were unable to get Romi to consistently begin following the line again after navigating the obstacle, and were unable to capture it on video. Similarly, returning to start was not achieved consistently either, although attempts to do so were made.',['../index.html#autotoc_md12',1,'']]],
  ['consistently_20either_20although_20attempts_20to_20do_20so_20were_20made_5',['Video showing Romi traveling from the start block to the far side of the obstacle. Romi navigates along the path using its reflectance sensor until it hits the obstacle. Then, Romi uses an IMU to navigate around the wall according to its heading. Unfortunately, we were unable to get Romi to consistently begin following the line again after navigating the obstacle, and were unable to capture it on video. Similarly, returning to start was not achieved consistently either, although attempts to do so were made.',['../index.html#autotoc_md12',1,'']]],
  ['cotask_2epy_6',['cotask.py',['../cotask_8py.html',1,'']]]
];
